"""phase2_authoritative_schema

Revision ID: cb280e8353a3
Revises: cb628149b660
Create Date: 2026-09-23 00:56:05.475738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb280e8353a3'
down_revision: Union[str, Sequence[str], None] = 'cb628149b660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assay_profiles',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('profile_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manufacturer_or_source', sa.String(length=128), nullable=True),
    sa.Column('reference_card_version', sa.String(length=64), nullable=False),
    sa.Column('t_min_seconds', sa.Float(), nullable=False),
    sa.Column('t_max_seconds', sa.Float(), nullable=False),
    sa.Column('kinetic_window_required', sa.Boolean(), nullable=False),
    sa.Column('threshold_configuration', sa.JSON(), nullable=True),
    sa.Column('calibration_targets', sa.JSON(), nullable=True),
    sa.Column('classifier_configuration', sa.JSON(), nullable=True),
    sa.Column('reaction_start_definition', sa.String(length=64), nullable=True),
    sa.Column('reaction_roi_definition', sa.JSON(), nullable=True),
    sa.Column('profile_effective_from_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_effective_until_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_snapshot_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('profile_id', 'profile_version')
    )
    op.create_index(op.f('ix_assay_profiles_profile_id'), 'assay_profiles', ['profile_id'], unique=False)
    op.create_table('device_enrollments',
    sa.Column('device_enrollment_id', sa.String(length=64), nullable=False),
    sa.Column('device_platform', sa.String(length=64), nullable=False),
    sa.Column('device_attestation_id', sa.String(length=128), nullable=True),
    sa.Column('public_key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issuer_id', sa.String(length=64), nullable=False),
    sa.Column('registry_version', sa.String(length=32), nullable=False),
    sa.Column('enrolled_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revoked_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=256), nullable=True),
    sa.Column('enrollment_record_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('device_enrollment_id')
    )
    op.create_index(op.f('ix_device_enrollments_device_enrollment_id'), 'device_enrollments', ['device_enrollment_id'], unique=False)
    op.create_table('test_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('field_officer_name', sa.String(length=128), nullable=True),
    sa.Column('field_officer_designation', sa.String(length=64), nullable=True),
    sa.Column('police_station_jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('assay_profile_id', sa.String(length=64), nullable=False),
    sa.Column('assay_profile_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capture_mode', sa.String(length=32), nullable=False),
    sa.Column('gps_status', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=256), nullable=True),
    sa.Column('sync_state', sa.String(length=32), nullable=False),
    sa.Column('device_enrollment_id', sa.String(length=64), nullable=False),
    sa.Column('signing_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sessions_case_id'), 'test_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_test_sessions_id'), 'test_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_test_sessions_operator_id'), 'test_sessions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_test_sessions_status'), 'test_sessions', ['status'], unique=False)
    op.create_table('trusted_key_registry',
    sa.Column('registry_version', sa.String(length=32), nullable=False),
    sa.Column('issuer_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registry_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('registry_signature', sa.String(length=256), nullable=False),
    sa.Column('authority_key_fingerprint', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('registry_version')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('device_enrollment_id', sa.String(length=64), nullable=False),
    sa.Column('event_payload', sa.JSON(), nullable=True),
    sa.Column('event_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_test_id'), 'audit_events', ['test_id'], unique=False)
    op.create_table('capture_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('captured_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_records_id'), 'capture_records', ['id'], unique=False)
    op.create_index(op.f('ix_capture_records_session_id'), 'capture_records', ['session_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('image_reference', sa.String(length=256), nullable=True),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('canonical_record_json', sa.Text(), nullable=True),
    sa.Column('record_digest', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('public_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('signing_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('device_enrollment_id', sa.String(length=64), nullable=False),
    sa.Column('trust_registry_version', sa.String(length=32), nullable=False),
    sa.Column('signing_device_authorization_status', sa.String(length=32), nullable=False),
    sa.Column('previous_record_hash', sa.String(length=64), nullable=True),
    sa.Column('integrity_status', sa.String(length=32), nullable=False),
    sa.Column('sealed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_records_test_id'), 'evidence_records', ['test_id'], unique=True)
    op.create_table('measurement_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('card_detection_confidence', sa.Float(), nullable=True),
    sa.Column('calibration_residual', sa.Float(), nullable=True),
    sa.Column('blur_metric', sa.Float(), nullable=True),
    sa.Column('exposure_metric', sa.Float(), nullable=True),
    sa.Column('glare_metric', sa.Float(), nullable=True),
    sa.Column('roi_pixel_count', sa.Integer(), nullable=True),
    sa.Column('specular_rejected_pixel_count', sa.Integer(), nullable=True),
    sa.Column('specular_rejected_fraction', sa.Float(), nullable=True),
    sa.Column('roi_sampling_method', sa.String(length=32), nullable=True),
    sa.Column('roi_kmeans_k', sa.Integer(), nullable=True),
    sa.Column('selected_cluster_id', sa.Integer(), nullable=True),
    sa.Column('selected_cluster_area_fraction', sa.Float(), nullable=True),
    sa.Column('reaction_lab_l', sa.Float(), nullable=True),
    sa.Column('reaction_lab_a', sa.Float(), nullable=True),
    sa.Column('reaction_lab_b', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('class_distance_1', sa.Float(), nullable=True),
    sa.Column('class_distance_2', sa.Float(), nullable=True),
    sa.Column('decision_margin', sa.Float(), nullable=True),
    sa.Column('classifier_invocation_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_results_test_id'), 'measurement_results', ['test_id'], unique=True)
    op.create_table('procedural_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('search_context_type', sa.String(length=64), nullable=True),
    sa.Column('authorization_reference', sa.String(length=128), nullable=True),
    sa.Column('panchnama_memo_ref_no', sa.String(length=128), nullable=True),
    sa.Column('panch_witness_1_name', sa.String(length=128), nullable=True),
    sa.Column('panch_witness_2_name', sa.String(length=128), nullable=True),
    sa.Column('procedural_safeguard_status', sa.String(length=64), nullable=True),
    sa.Column('section_50_status', sa.String(length=64), nullable=True),
    sa.Column('section_50_choice_recorded', sa.String(length=64), nullable=True),
    sa.Column('gazetted_officer_or_magistrate_reference', sa.String(length=128), nullable=True),
    sa.Column('inventory_ref_no', sa.String(length=128), nullable=True),
    sa.Column('section_52a_reference', sa.String(length=128), nullable=True),
    sa.Column('sample_identifier', sa.String(length=64), nullable=True),
    sa.Column('seal_identifier', sa.String(length=64), nullable=True),
    sa.Column('sample_drawal_status', sa.String(length=64), nullable=True),
    sa.Column('magistrate_certification_status', sa.String(length=64), nullable=True),
    sa.Column('section_57_report_ref_no', sa.String(length=128), nullable=True),
    sa.Column('section_57_report_status', sa.String(length=64), nullable=True),
    sa.Column('officer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedural_context_test_id'), 'procedural_context', ['test_id'], unique=True)
    op.create_table('reaction_timing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('reaction_started_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_timestamp_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('timer_source', sa.String(length=32), nullable=False),
    sa.Column('kinetic_window_status', sa.String(length=32), nullable=False),
    sa.Column('t_min_seconds_snapshot', sa.Float(), nullable=False),
    sa.Column('t_max_seconds_snapshot', sa.Float(), nullable=False),
    sa.Column('reaction_start_event_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_timing_test_id'), 'reaction_timing', ['test_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_timing_test_id'), table_name='reaction_timing')
    op.drop_table('reaction_timing')
    op.drop_index(op.f('ix_procedural_context_test_id'), table_name='procedural_context')
    op.drop_table('procedural_context')
    op.drop_index(op.f('ix_measurement_results_test_id'), table_name='measurement_results')
    op.drop_table('measurement_results')
    op.drop_index(op.f('ix_evidence_records_test_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_capture_records_session_id'), table_name='capture_records')
    op.drop_index(op.f('ix_capture_records_id'), table_name='capture_records')
    op.drop_table('capture_records')
    op.drop_index(op.f('ix_audit_events_test_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('trusted_key_registry')
    op.drop_index(op.f('ix_test_sessions_status'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_operator_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_case_id'), table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_index(op.f('ix_device_enrollments_device_enrollment_id'), table_name='device_enrollments')
    op.drop_table('device_enrollments')
    op.drop_index(op.f('ix_assay_profiles_profile_id'), table_name='assay_profiles')
    op.drop_table('assay_profiles')
    # ### end Alembic commands ###
